const SET_TITLE = 'SET_TITLE',
      SET_DESC = 'SET_DESC',
      SET_CREATED_TIME = 'SET_CREATED_TIME',
      SET_UPDATED_TIME = 'SET_UPDATED_TIME',
      SET_CONTENT = 'SET_CONTENT'

export {
  SET_TITLE,
  SET_DESC,
  SET_CREATED_TIME,
  SET_UPDATED_TIME,
  SET_CONTENT
}